version: '3.8'

services:

  # Servicio PHP con Apache 
  php:
    build: .
    restart: always
    ports:
      - "80:80"           # Puerto 80 del PC apunta al puerto 80 del contenedor
    depends_on:
      - db                # Espera a que la base de datos esté lista
    environment:
      DB_HOST: db
      DB_NAME: apptiempo
      DB_USER: antonio
      DB_PASS: antonio
    volumes:
      - .:/var/www/html   # Los cambios en el código se ven al instante

  # Servicio MariaDB (base de datos)
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: apptiempo
      MYSQL_USER: antonio
      MYSQL_PASSWORD: antonio
    volumes:
      - datos_db:/var/lib/mysql   # Los datos persisten aunque pares el contenedor

# Volumen para guardar los datos de la base de datos
volumes:
  datos_db:
